name: Scan

on:
  workflow_call:
    inputs:
      ref:
        type: string

jobs:
  scan:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Security Scan - Truffle Enterprise / SAST
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:
          args: --quiet

      - name: Security Scan - Truffle Open Source / SAST
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: '--regex --entropy=False --max_depth=10 --rules /regexes.json'
